name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 
      run: git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep -E '\.(cpp|hpp)$' | xargs clang-format -i -style=file && git diff --exit-code

  build:
    needs: check-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up CMake
      run: sudo apt-get install cmake
    - name: Build
      run: mkdir build && cmake -S . build/ && cmake --build build/
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: build

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/download-artifact@v1
  #     with:
  #       name: build
  #   - name: Run
  #     run: ./build/WordleSolver

  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   - name: Build and push
  #     uses: docker/build-push-action@v4
  #     with:
  #       push: true
  #       tags: user/app:latest