name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          wget -O cmake-linux.sh https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3-linux-x86_64.sh
          chmod +x cmake-linux.sh
          ./cmake-linux.sh --skip-license --prefix=/usr/local
          rm cmake-linux.sh

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
