name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest #22.04-16core
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: sudo apt-get install cmake

    - name: Build
      run: |
        mkdir build
        cmake -S . -B build
        cmake --build build/
    - name: Run tests
      run: ./build/tests

  # test:
  #   runs-on: ubuntu-latest #22.04-16core
  #   needs: build
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Install CMake
  #     run: sudo apt-get install cmake

  #   - name: Build
  #     run: |
  #       mkdir build
  #       cmake -S . -B build
  #       cmake --build build/

  #   - name: Run tests
  #     run: |
  #       cd build
  #       tests
