name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest #22.04-16core
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: |
        mkdir build
        cmake -S . -B build
        cmake --build build/

    - name: Run tests
      run: cd build && ctest

    - name: Run executable
      run: ./build/WordleSolver ra cloud ra+ cloud bl cloud red cloud en cloud

